List<Map<String, dynamic>> mockRecipes = [
  {
    "id": "1",
    "title": "Борщ классический",
    "description": "Традиционный русский суп со свеклой и капустой",
    "tags": ["суп", "русская кухня", "обед"],
    "image":
        "https://azbyka.ru/recept/wp-content/uploads/2024/11/borsch-traditional-ukrainian-russian-beetroot-soup-dark-wooden-background-1.jpg",
    "components": [
      "Говядина",
      "Свекла",
      "Картофель",
      "Капуста",
      "Морковь",
      "Лук",
      "Томатная паста",
    ],
    "approximateTime": "2 часа",
    "calories": 250,
    "difficulty": "средняя",
  },
  {
    "id": "2",
    "title": "Жареная курица с картофелем",
    "description": "Простое и вкусное блюдо для ужина",
    "tags": ["ужин", "курица", "простое"],
    "image":
        "https://www.koolinar.ru/all_image/recipes/132/132747/recipe_2ec09d9f-2a9a-4d2b-950a-cb6ab69a1189.jpg",
    "components": [
      "Курица",
      "Картофель",
      "Чеснок",
      "Масло растительное",
      "Соль",
      "Перец",
    ],
    "approximateTime": "1 час",
    "calories": 450,
    "difficulty": "легкая",
  },
  {
    "id": "3",
    "title": "Овсянка на молоке",
    "description": "Полезный завтрак с медом и ягодами",
    "tags": ["завтрак", "полезное", "быстрое"],
    "image":
        "https://yandex-images.clstorage.net/oHz100317/f38c33Yqr/H4QNEdTmNIzgLLE8lh2AS7EIqSGN1P4wthQqblbZZT9xeeB6_ztAb-sippUQc4w81MmKP2DJLebPdMhdyc2CwlKFbBiZ_02Q4DjgEL8t6HvxXZlUgYH2VKYJTl5TcZWikfkRnjObyNNeGra0ZSaJHdHIIs8xIETPuyUoUS1gj8erhCV97AbNcLy4bGxCgVwbfaEZjdmhcgFqtGu7QzUllkGZeSrTE8hPbmYGMF0K7Bl9EOKWoTxErz-BsB2poAvPV7StCfz-yQB0KFjMzkXQeznlCcX5FU7B2rybT08ZWeIB4aW6p3tgF-7ONpDtagBx8bj6lrUgGHtD4SAFpSgPcy9g1dlEekEEdHTcrLIhrJP9ORnxHSXexS4EB7tfVQlGxTWl5sc3EP82qnKkwfY8xU3IHi6BuGBnT22Qqb0U60cLCC352CrpcORsqMCmTWh_rYGNnQlZJgViODefw-Vh-qEZ2ebrZ-C3di4iKMH-RCFF0PqeLRAQq-NNqB0V8BsHO4ztofzOnZi8NBjI0g2Igx2NXf3Z4W5ZruCPI98BUR5VUdEGTyNIxwIugkgt6uBBLXSGHqHkHMNDLaTVXVw7B4dQueVger2gZFh4nOZ5vMPFOZ0dnUliBZYI_z_TmdV-xeEpxhMLfMcyRjrIxXKwtfmsbm55FGjDn0UIlem440_XVMXZTKI9JGCswKDCeSDrHXnZ1RVBfslGKIdPE1mtjqn9KQq_i5TnXtpuCDGmXO3FCEIq4SBEE1MxMEn9zH9fw0AZ_RxyneC8dMyQdj1wVz0xmXGd4WYh-vAre1c9zQohlYl2f5PAE-rWKjDVauCdQSC2Ev2sZAvfofzZ8RxzN4_UJaFYctXUvGj41JrB_B9NTdkt2UVKPVIcHxczvc2GrdVBemvjQE_ebmK8FWoMkaEA5rb1tFjDq3kcZYHQYzeTbKWpDDbl-MCIZGReoZy76X09MQmtmsV6lI9XlwV0",
    "components": ["Овсянка", "Молоко", "Мед", "Черника", "Бананы"],
    "approximateTime": "10 мин",
    "calories": 300,
    "difficulty": "легкая",
  },
  {
    "id": "4",
    "title": "Паста Карбонара",
    "description": "Итальянская паста с беконом и сливками",
    "tags": ["паста", "итальянская кухня", "ужин"],
    "image": "https://profile.ru/wp-content/uploads/1820740-fb.jpeg",
    "components": ["Макароны", "Бекон", "Сливки", "Яйца", "Сыр", "Чеснок"],
    "approximateTime": "30 мин",
    "calories": 550,
    "difficulty": "средняя",
  },
  {
    "id": "5",
    "title": "Греческий салат",
    "description": "Свежий салат с овощами и фетой",
    "tags": ["салат", "здоровое питание", "лето"],
    "image": "https://app.ivinsight.ru/uploads/recipes/1644850758.jpeg",
    "components": [
      "Помидоры",
      "Огурцы",
      "Перец болгарский",
      "Лук",
      "Сыр",
      "Оливковое масло",
      "Оливки",
    ],
    "approximateTime": "15 мин",
    "calories": 200,
    "difficulty": "легкая",
  },
  {
    "id": "6",
    "title": "Рис с курицей и овощами",
    "description": "Сытное блюдо азиатской кухни",
    "tags": ["рис", "курица", "ужин"],
    "image":
        "https://avatars.mds.yandex.net/i?id=339ae4e8c0374371fbe8ddcd7863b90d_l-5621412-images-thumbs&n=13",
    "components": [
      "Рис",
      "Курица",
      "Морковь",
      "Перец болгарский",
      "Лук",
      "Соевый соус",
      "Чеснок",
    ],
    "approximateTime": "45 мин",
    "calories": 400,
    "difficulty": "средняя",
  },
  {
    "id": "7",
    "title": "Блины на молоке",
    "description": "Тонкие блины с начинкой или без",
    "tags": ["завтрак", "выпечка", "традиционное"],
    "image": "https://img.povar.ru/icook/uploads/0d/70/24/67/97371.jpg",
    "components": [
      "Мука",
      "Молоко",
      "Яйца",
      "Сахар",
      "Масло сливочное",
      "Соль",
    ],
    "approximateTime": "40 мин",
    "calories": 350,
    "difficulty": "средняя",
  },
  {
    "id": "8",
    "title": "Тушеная капуста с мясом",
    "description": "Домашнее блюдо с говядиной",
    "tags": ["ужин", "мясо", "домашнее"],
    "image":
        "https://static.1000.menu/files/user-v2/78/22/661109/foto/f_17-05-2023-07-37-03.1684352224.jpg",
    "components": [
      "Капуста",
      "Говядина",
      "Лук",
      "Морковь",
      "Томатная паста",
      "Соль",
      "Перец",
    ],
    "approximateTime": "90 мин",
    "calories": 380,
    "difficulty": "средняя",
  },
  {
    "id": "9",
    "title": "Фруктовый смузи",
    "description": "Освежающий напиток из свежих фруктов",
    "tags": ["напиток", "здоровое", "быстрое"],
    "image":
        "https://images.gastronom.ru/UGFxAYkqQdXvno7l9Ox06NuU7NZBMwIPqvgeKQvAero/pr:recipe-cover-image/g:ce/rs:auto:0:0:0/L2Ntcy9hbGwtaW1hZ2VzL2Q1ZjU2ZGY2LWE0N2EtNGJjOS04MGM5LTIyMGE4ZWYwYWJjMC5qcGc.webp",
    "components": ["Бананы", "Клубника", "Йогурт", "Мед", "Молоко"],
    "approximateTime": "5 мин",
    "calories": 180,
    "difficulty": "легкая",
  },
  {
    "id": "10",
    "title": "Запеченная рыба с лимоном",
    "description": "Диетическое блюдо с рыбой",
    "tags": ["рыба", "диетическое", "ужин"],
    "image":
        "https://cdn.lifehacker.ru/wp-content/uploads/2024/12/301_1734696857.jpg",
    "components": [
      "Рыба",
      "Лимоны",
      "Чеснок",
      "Укроп",
      "Масло растительное",
      "Соль",
    ],
    "approximateTime": "40 мин",
    "calories": 280,
    "difficulty": "легкая",
  },
  {
    "id": "11",
    "title": "Омлет с сыром",
    "description": "Быстрый завтрак на сковороде",
    "tags": ["завтрак", "яйца", "быстрое"],
    "components": ["Яйца", "Сыр", "Молоко", "Масло сливочное", "Соль", "Перец"],
    "image": "https://lafoy.ru/photo_l/foto-3950-15.jpg",
    "approximateTime": "10 мин",
    "calories": 320,
    "difficulty": "легкая",
  },
  {
    "id": "12",
    "title": "Плов с бараниной",
    "description": "Традиционное восточное блюдо",
    "tags": ["рис", "баранина", "восточная кухня"],
    "image":
        "https://cdn.food.ru/unsigned/fit/640/480/ce/0/czM6Ly9tZWRpYS9waWN0dXJlcy8yMDI0MTAxNy91QlBBM0IuanBlZw.jpg",
    "components": [
      "Рис",
      "Баранина",
      "Морковь",
      "Лук",
      "Чеснок",
      "Специи",
      "Масло растительное",
    ],
    "approximateTime": "90 мин",
    "calories": 500,
    "difficulty": "сложная",
  },
  {
    "id": "13",
    "title": "Творожная запеканка",
    "description": "Нежная запеканка с изюмом",
    "tags": ["десерт", "творог", "выпечка"],
    "image":
        "https://gotovim-doma.ru/images/recipe/b/84/b843288d5328c9582f78b0ae6a23f71f.jpg",
    "components": ["Творог", "Яйца", "Сахар", "Изюм", "Сметана", "Манка"],
    "approximateTime": "60 мин",
    "calories": 290,
    "difficulty": "средняя",
  },
  {
    "id": "14",
    "title": "Спагетти Болоньезе",
    "description": "Итальянская паста с мясным соусом",
    "tags": ["паста", "мясо", "ужин"],
    "image":
        "https://img.povar.ru/uploads/53/5d/db/1e/pasta_quotbolonezequot_s_sirom-798919.jpg",
    "components": [
      "Макароны",
      "Говядина",
      "Помидоры",
      "Лук",
      "Чеснок",
      "Томатная паста",
      "Специи",
    ],
    "approximateTime": "50 мин",
    "calories": 480,
    "difficulty": "средняя",
  },
  {
    "id": "15",
    "title": "Овощное рагу",
    "description": "Легкое вегетарианское блюдо",
    "tags": ["овощи", "вегетарианское", "ужин"],
    "image":
        "https://static.1000.menu/img/content-v2/47/cd/66415/ragu-ovoshchnoe-v-kazane_1657865547_19_max.jpg",
    "components": [
      "Кабачки",
      "Баклажаны",
      "Перец болгарский",
      "Помидоры",
      "Лук",
      "Чеснок",
      "Зелень",
    ],
    "approximateTime": "45 мин",
    "calories": 180,
    "difficulty": "легкая",
  },
  {
    "id": "16",
    "title": "Куриный суп с лапшой",
    "description": "Домашний куриный бульон с домашней лапшой",
    "tags": ["суп", "курица", "домашнее"],
    "image":
        "https://main-cdn.sbermegamarket.ru/big1/hlr-system/-15/970/316/851/181/64/100029622948b0.jpg",
    "components": [
      "Курица",
      "Лапша",
      "Морковь",
      "Лук",
      "Яйца",
      "Мука",
      "Зелень",
    ],
    "approximateTime": "90 мин",
    "calories": 220,
    "difficulty": "средняя",
  },
  {
    "id": "17",
    "title": "Салат Цезарь",
    "description": "Классический салат с курицей и сухариками",
    "tags": ["салат", "курица", "популярное"],
    "image":
        "https://avatars.mds.yandex.net/i?id=22cce8c36d44132435d7b7da8629a1c8_l-10915333-images-thumbs&n=13",
    "components": [
      "Курица",
      "Салат",
      "Сухари",
      "Сыр",
      "Яйца",
      "Майонез",
      "Чеснок",
    ],
    "approximateTime": "25 мин",
    "calories": 350,
    "difficulty": "легкая",
  },
  {
    "id": "18",
    "title": "Гречка с грибами",
    "description": "Простое и сытное блюдо",
    "tags": ["гречка", "грибы", "ужин"],
    "image":
        "https://www.photorecept.ru/wp-content/uploads/2021/04/grechnevaja-kasha-s-gribami-1300x867.jpg",
    "components": [
      "Гречка",
      "Грибы",
      "Лук",
      "Масло сливочное",
      "Соль",
      "Перец",
    ],
    "approximateTime": "35 мин",
    "calories": 320,
    "difficulty": "легкая",
  },
  {
    "id": "19",
    "title": "Шарлотка с яблоками",
    "description": "Простой яблочный пирог",
    "tags": ["десерт", "яблоки", "выпечка"],
    "image":
        "https://avatars.mds.yandex.net/i?id=fdbb6fd07e8a9d75e4b56a91228301bc_l-5232530-images-thumbs&n=13",
    "components": [
      "Яблоки",
      "Мука",
      "Яйца",
      "Сахар",
      "Масло сливочное",
      "Разрыхлитель",
    ],
    "approximateTime": "50 мин",
    "calories": 280,
    "difficulty": "легкая",
  },
  {
    "id": "20",
    "title": "Котлеты из индейки",
    "description": "Диетические котлеты на пару",
    "tags": ["котлеты", "индейка", "диетическое"],
    "image":
        "https://cdn.lifehacker.ru/wp-content/uploads/2019/07/Depositphotos_140441374_xl-2015_1562048395-e1562048441430-2000x1000.jpg",
    "components": ["Индейка", "Лук", "Хлеб", "Молоко", "Яйца", "Соль", "Перец"],
    "approximateTime": "40 мин",
    "calories": 250,
    "difficulty": "средняя",
  },
  {
    "id": "21",
    "title": "Макароны с сыром",
    "description": "Быстрое блюдо для студентов",
    "tags": ["макароны", "сыр", "быстрое"],
    "image":
        "https://cdnn21.img.ria.ru/images/07e9/02/0c/1998784388_0:160:3072:1888_1920x0_80_0_0_aca74004ce2da688a95d1602aa656e69.jpg",
    "components": ["Макароны", "Сыр", "Масло сливочное", "Молоко", "Соль"],
    "approximateTime": "15 мин",
    "calories": 400,
    "difficulty": "легкая",
  },
  {
    "id": "22",
    "title": "Тыквенный суп-пюре",
    "description": "Нежный осенний суп",
    "tags": ["суп", "тыква", "осень"],
    "image":
        "https://static.1000.menu/img/content/30273/sup-pure-iz-tykvy-klassicheskii_1545215004_1_max.jpg",
    "components": [
      "Тыква",
      "Картофель",
      "Лук",
      "Сливки",
      "Масло сливочное",
      "Соль",
      "Перец",
    ],
    "approximateTime": "45 мин",
    "calories": 180,
    "difficulty": "легкая",
  },
  {
    "id": "23",
    "title": "Куриные крылышки BBQ",
    "description": "Острые крылышки в соусе барбекю",
    "tags": ["курица", "закуска", "острое"],
    "image":
        "https://avatars.mds.yandex.net/i?id=9cf23f9fbf17beab0ccaa843e6f9c262_sr-4389814-images-thumbs&n=13",
    "components": [
      "Курица",
      "Кетчуп",
      "Горчица",
      "Мед",
      "Соевый соус",
      "Чеснок",
      "Специи",
    ],
    "approximateTime": "50 мин",
    "calories": 420,
    "difficulty": "средняя",
  },
  {
    "id": "24",
    "title": "Рисовая каша с молоком",
    "description": "Классический завтрак для детей",
    "tags": ["завтрак", "рис", "детское"],
    "image":
        "https://cdn.food.ru/unsigned/fit/640/480/ce/0/czM6Ly9tZWRpYS9waWN0dXJlcy8yMDI1MDQxNy80QVhDRUMuanBlZw.jpg",
    "components": ["Рис", "Молоко", "Сахар", "Масло сливочное", "Соль"],
    "approximateTime": "25 мин",
    "calories": 280,
    "difficulty": "легкая",
  },
  {
    "id": "25",
    "title": "Стейк из говядины",
    "description": "Сочный стейк средней прожарки",
    "tags": ["мясо", "говядина", "ужин"],
    "image":
        "https://avatars.mds.yandex.net/get-vertis-journal/4220003/564e2ae5-e710-4220-bddc-3710f01f2173.jpg/1600x1600",
    "components": [
      "Говядина",
      "Масло сливочное",
      "Чеснок",
      "Розмарин",
      "Соль",
      "Перец",
    ],
    "approximateTime": "20 мин",
    "calories": 550,
    "difficulty": "средняя",
  },
];
